steps:
  # Dockerイメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/built-in-ai-challenge-api:$BUILD_ID"
      - "-t"
      - "gcr.io/$PROJECT_ID/built-in-ai-challenge-api:latest"
      - "."

  # Container Registryにプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "gcr.io/$PROJECT_ID/built-in-ai-challenge-api"

  # Cloud Runにデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "built-in-ai-challenge-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/built-in-ai-challenge-api:$BUILD_ID"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "10"
      - "--set-env-vars"
      - "NODE_ENV=production"

# ビルドされたイメージ（Cloud Build履歴に記録）
images:
  - "gcr.io/$PROJECT_ID/built-in-ai-challenge-api:$BUILD_ID"
  - "gcr.io/$PROJECT_ID/built-in-ai-challenge-api:latest"

options:
  logging: CLOUD_LOGGING_ONLY
